### ISSUE TITLE
Perihal tabel migrasi

### ISSUE THREAD

**Issue by indralaksmana** [bantenprov/laravel-opd#16]
Untuk versi 1.0.1 ini, tabel hasil migrasi nya apa ya? 
Soalnya, setelah saya install yang baru. Tabel yang dimigrasi tetap  "ref_unitkerjas". Sedang kan yang digunakan dalam modelnya sudah barubah menjadi tabel "opd".

**Comment by anjjriit** [comment]
apakah ini dari "clean install "?
bisa lihat disini [2017_11_08_053023_create_laravel_opd_table](
https://github.com/bantenprov/laravel-opd/blob/1.0.1/src/database/migrations/2017_11_08_053023_create_laravel_opd_table.php).

**Comment by anjjriit** [comment]
sudah ada demo [laravel-opd](http://opd-01.dev.bantenprov.go.id/laravel-opd#table-display) nya.,
kalau ada kekeliruan kirim patch.
trims

**Comment by andri-sudarmawijaya** [comment]
ini dari fresh install kah ?
please recheck code disini [2017_11_08_053023_create_laravel_opd_table](https://github.com/bantenprov/laravel-opd/blob/1.0.1/src/database/migrations/2017_11_08_053023_create_laravel_opd_table.php).

**Comment by andri-sudarmawijaya** [comment]
sudah ada demo [laravel-opd](http://opd-01.dev.bantenprov.go.id/laravel-opd#table-display).
tolong kirim patch untuk perbaikan dan pengembangannya
